### ISSUE TITLE
Update MSAL to 1.1.4-preview

### ISSUE THREAD

**Issue by jennyf19** [Azure-Samples/xamarin-azure-businessreview#2]
**Minimal steps to reproduce:**
Clone and build the repo. Try to update Nuget package for MSAL and get an error that the source is not found for Nuget packages in Reviewer.Droid and Reviewer.iOS. [Customer](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/561) cannot update MSAL nuget package.

 ![image](https://user-images.githubusercontent.com/19942418/40570239-885cb696-603d-11e8-9039-17356d272caf.png)

**Expected behavior:**
User can update MSAL through Nuget Package Manager. Please update [MSAL to 1.1.4-preview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/1.1.4-preview). 
We have released MSAL 1.1.3-preview, which includes support for Xamarin.Android.Support 27.0.2 and MonoAndroid8.1. Thank you!

**Comment by codemillmatt** [comment]
Issue via VS Mac having the NuGet package cached

**Comment by codemillmatt** [comment]
1.1.4 merged into master

**Comment by jennyf19** [comment]
Thanks @codemillmatt
